name: Docker CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker CI
      run: |
        export BUILD_NUM=$(date -u +"%y%m%d%H%M")

        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPO }}/helium-csharp:${BUILD_NUM}
        
        docker tag ${{ secrets.DOCKER_REPO }}/helium-csharp:${BUILD_NUM} ${{ secrets.DOCKER_REPO }}/helium-csharp:stable

        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PAT }}

        docker push ${{ secrets.DOCKER_REPO }}/helium-csharp:${BUILD_NUM}
        docker push ${{ secrets.DOCKER_REPO }}/helium-csharp:stable
