name: DockerCI-PR

on:
  pull_request:
    branches:
      - master

    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'saveenv.sh'

jobs:

  docker-build-push:

    runs-on: ubuntu-latest
    env:
      #  DOCKER_REPO  - the docker repository name in the form: organization/repository
      DOCKER_REPO: 'retaildevcrew/helium-csharp'

    steps:
    - uses: actions/checkout@v1

    - name: Build Container
      run: |
        # testing az
        echo $PATH
        
        az login --service-principal  -u ${{ secrets.SERVICE_PRINCIPAL }} --tenant ${{ secrets.TENANT }} -p ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        az account get-access-token --output json --resource https://vault.azure.net
